### ISSUE TITLE
Adjust w3id referrals

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-dataspace-protocol-base/DataspaceProtocol#12]
Currently, the `dspace` namespace in w3id [1] points to the "old" repo's github-pages at IDSA. When the actions are deployed in this new repo, that should reflect in the w3id resolution logic.

[1] https://github.com/perma-id/w3id.org/blob/master/dspace/.htaccess

**Comment by ssteinbuss** [comment]
The GitHub pages for this repo are online. The W3ids are prepared [here](https://github.com/International-Data-Spaces-Association/w3id.org/pull/12/files). Needs a final check before merging.

**Comment by ssteinbuss** [comment]
PR to w3id repository issued

**Comment by ssteinbuss** [comment]
Merged, issue may be closed
