### ISSUE TITLE
Bring back commit history

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-dataspace-protocol-base/DataspaceProtocol#19]
The initial contribution erased the commit history. I think, it should be brought back because motivation and progress provide important context for discussions in the future.

cc @ssteinbuss

**Comment by ssteinbuss** [comment]
The commit history is not erased by available in the [IDSA Dataspace Protocol Respository](https://github.com/International-Data-Spaces-Association/ids-specification). It was decided to start contributing the content, but not the commit history.
