### ISSUE TITLE
common/common.protocol.md: Link to SHACL Shape points to empty file

### ISSUE THREAD

**Issue by k00ni** [eclipse-dataspace-protocol-base/DataspaceProtocol#35]
# Bug Report

## Describe the Bug

I am not sure what to expect here, but in the document https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/blob/main/common/common.protocol.md 

![Bildschirmfoto vom 2024-09-30 12-37-27](https://github.com/user-attachments/assets/b9b73d81-b6ed-42b8-ae87-017593cd9a1c)

its stated:

> This data object must comply to the JSON Schema **and the [SHACL Shape](https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/blob/main/common/shape/version-shape.ttl)**.

But the SHACL Shape file https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/blob/main/common/shape/version-shape.ttl is empty.

### Expected Behavior

A file with more than 0 lines of code.

### Observed Behavior

Empty file.

**Comment by jimmarino** [comment]
Closing this as SHACL is being removed from the specification.
