### ISSUE TITLE
Project Requires a Code of Conduct

### ISSUE THREAD

**Issue by ssteinbuss** [eclipse-dataspace-protocol-base/DataspaceProtocol#4]
To maintain a healthy, welcoming, and respectful environment within our community, it is essential that we establish a Code of Conduct. A Code of Conduct outlines our expectations for participant behavior as well as the consequences for unacceptable behavior.

I recommend that we adopt the Eclipse Code of Conduct for our project. The Eclipse Code of Conduct is well-established, comprehensive, and aligns well with our community values.

## Proposed Solution:

Adopt the Eclipse Code of Conduct: You can find the full text of the Eclipse Code of Conduct [here](https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php). We should review this document and agree to adopt it for our project.

Create a CODE_OF_CONDUCT.md file: Once we agree on adopting the Eclipse Code of Conduct, we should create a CODE_OF_CONDUCT.md file in the root directory of our repository and include the full text of the Eclipse Code of Conduct in this file.

Update the repository documentation: We should update our README and CONTRIBUTING documents to reference and link to our new Code of Conduct.

## Benefits:

* Ensures a welcoming and inclusive environment for all contributors.
* Clearly communicates our community expectations and standards.
* Provides a mechanism for reporting and addressing violations of the Code of Conduct.

## Action Items:

- [x] Review the Eclipse Code of Conduct.
- [x] Discuss and agree on its adoption for our project.
- [x] Create and commit the CODE_OF_CONDUCT.md file with the adopted text.
- [ ] Update the repository documentation to reference the Code of Conduct.

**Comment by juliapampus** [comment]
> and include the full text of the Eclipse Code of Conduct in this file
I would just link to the text of the Eclipse Code of Conduct to avoid duplication. See [here](https://github.com/eclipse-edc/docs/blob/main/CONTRIBUTING.md#code-of-conduct) for a sample text.

**Comment by ssteinbuss** [comment]
Avoiding duplication is a fair point. On the other side, the project shall meet the community standards, which are measured automatically, by the existence of a Code of Conduct file and not by linking to on. Therefore, I would propose to create a Code of Conduct file based on the Eclipse Code of Conduct to ease our lives.
