### ISSUE TITLE
Remove reference to `dspace-trust`

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspace-protocol-base/DataspaceProtocol#47]
# Bug Report

The reference to `/.well-known/dspace-trust` in the catalog binding chapter should be removed and dealt with in the DCP specification.

**Comment by arnoweiss** [comment]
added an issue in DCP. PR here will follow.
https://github.com/eclipse-dataspace-dcp/decentralized-claims-protocol/issues/113
