### ISSUE TITLE
Contract `LeftOperand` and `Action` schemas use enums

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspace-protocol-base/DataspaceProtocol#48]
# Bug Report

The JSON schema `contract-schema.json` uses enums for `LeftOperand` and `Action` types. The type should be open-ended, e.g. `string`.

**Comment by sebbader-sap** [comment]
Is there a way to declare an open list in JSON Schema?

**Comment by jimmarino** [comment]
> Is there a way to declare an open list in JSON Schema?

I declared them as a list of strings in the Json schemas. This should be sufficient, correct?

**Comment by juliapampus** [comment]
Already fixed
