### ISSUE TITLE
Extract JSON schema/context files and validation 

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspace-protocol-base/DataspaceProtocol#50]
# Feature Request

Currently, JSON schema files are produced and verified manually in the specification repo. We should automate the production and verification of the schemas in a separate repo using an automated build system and JSON schema validator. In addition, we should include verification of JSON-LD expansion and compaction against the DSP Json-Ld context.

The produced JSON schemas and context can then be used in the specification documents.

**Comment by jimmarino** [comment]
> I don't have a strong opinion on keeping it all in one repo. We could adjust the existing links in the webpage. Pulling in examples from a remote source would be technically possible but might muddy the git-history as these changes might be breaking.

OK, I'll develop it in a separate repo for the time being. Later, assuming schema is the approach we want to take for the spec, the group can decide whether to merge or keep separate.

**Comment by jimmarino** [comment]
I created a proposal for this work in a separate repository as the changes are far-reaching. The repository can be accessed [here](https://github.com/jimmarino/dsp-schemas). 

I'd like to discuss this, but in the meantime, here is a recap of what is being proposed.

## Overview

The open-ended nature of Json-Ld and RDF-based technologies such as DCAT and ODRL, which DSP relies on, presents a number of challenges when defining a specification whose primary goal is interoperability. For example, these technologies allow for multiple serialization formats, data types, and ways of expressing the same meaning, which makes it difficult to establish a well-defined common ground for implementations to verify against. 

Since interoperability is our primary goal, we need a formal way to specify and validate all DSP message types and have that formal specification itself verified using a series of automated tests. A complimentary goal of interoperability is simplicity. We should also make it as easy as possible for implementations to meet mandatory DSP requirements, as this removes ambiguity introduced by complex features. 

Therefore, we should do the following:

1. Use Json Schema to formally specify all DSP messages and types. DSP Json schemas should be verified by automated testing. 
2. As part of automated testing, all example messages referenced in the specification text should be verified against their respective JSON schemas.
3. The DSP Json-Ld Context should be refactored to allow implementations to elect whether they will process messages as Json or Json-Ld. This is the same approach taken by the [W3C Verfiable Credentials Data Model 2.0 specification](https://www.w3.org/TR/vc-data-model-2.0/)
4. The DSP specification should provide its own ODRL profile. This profile should consist of a Json Schema and Json-Ld context that restricts ODRL's expressiveness to meet DSP use cases. The ODRL Json-Ld context will fix problems in the existing ODRL context and limit the number of terms.  
5. The DSP and ODRL Json-Ld contexts will be extensively verified using automated tests. These will consist of roundtrip testing that involves performing Json-Ld expansion and compaction on DSP messages and verifying the output against the associated Json schema. This roundtrip testing will validate the correctness of the Json-Ld contexts and terms and also ensure that non-Json-Ld-aware and Json-Ld-aware implementations can interoperate.
6. Json schema and Json-Ld contexts should be published as artifacts by an automated build

## Repository Contents and Next Steps

The repository contents perform steps 1-5 listed above (step 6 has not yet been implemented). If this approach is acceptable, we can decide whether the repository should be merged into the main specification repo or remain a standalone repository under the DSP project. At that point, the specification text can be updated to directly reference the verified examples and incorporate error corrections (cataloged below). The published schema artifacts will then be available to be used by the TCK and implementation projects.

**Comment by jimmarino** [comment]
The schemas are based on the existing repository schemas. I have fixed bugs and aligned the examples. Here is an list of the changes made:

##### `catalog-schema 1.json`
- Made all `@context` values an array:
```json
  "@context": [
    "https://w3id.org/dspace/2024/1/context.json"
  ]
```
- Removed `foaf:homepage` reference as it is not mandatory.

##### `dataset-schema.json`
- Removed all `dct` term except `dct:format` as they are not mandatory.

##### `dataset.v2.json`
- Removed all `dct` terms except `dct:format`.

##### `contract-schema.json`
- Removed `Action` enum and made it a `string`.
- `Constraint` is now modelled as a `LogicalConstraint` or an `AtomicContraints`. `LogicalConstraint` types are an `object` with a property array containing items of type `LogicalConstraint` or `AtomicContraint` (the schema supports recursive nesting).
- Removed `LeftOperand` `enum` and made it a `string` as the enum does not allow custom policy expressions.
- Made `RightOperand` a `string`, `object`, or `array`. See profile below for statement on why only string needs to be supported.
- Moved `assigner` and `assignee` to `Agreement` type from `AbstractPolicyRule`. Removed `AbstractPolicyRule` type as it is empty.  Adjusted `PolicyClass`, `MessageOffer`, and `RuleClass` to remove `allOf` since `AbstractPolicyRule` no longer exists.
- Removed `RuleClass` as it is not used
- Removed `minItems` on `Permission.constraint` property as constraints are not required per the ODRL spec. For example, it should be possible to write:

```json
     {
		  "@id": "urn:uuid:3dd1add8-4d2d-569e-d634-8394a8836a88",
		  "@type": "Agreement",
		  "target": "asset:1",
		  "assigner": "did:web:provider",
		  "assignee": "did:web:consumer",
		  "permission": [
			{
			  "action": "use"
			}
		  ]
	}
```

- Removed ODRL `rightOperandReference` as it is not mandatory in the specification and is potentially dangerous since it may require policy evaluators to download data from external endpoints.
- Added `lteq` to operator enum.
- Removed the requirement for `assigner` for Offer and MessageOffer types (only required for `Agreement` type).
- On `PolicyClass`, changed `profile` from `Reference` type to a `string` or `array`. This does not require it to be an array and can be a string. Also, this does not require it to be in `@id` form. For example, previously had to be expressed as:

```json
 "profile": [
    {
       "@id":"https://test.com/profile"
    }
    ],
```

now it can be:

```json
"profile": "https://test.com/profile"
```

- Made `leftOperand`, `rightOperand`, and `operand` properties required on `Constraint` type.
- Removed `@id` from `Duty`

###### `dataset-schema.json`
- Added @id to `Resource`
- Made `distribution` required on `Dataset`
- Made  the`accessService` property of `Distribution` be either a string or a `DataService` 

##### `catalog-schema.json`
- Introduced `RootCatalog`, which contains the mandatory `participantId`. Child `Catalog`s should not contain `participantId`s. 
- Added the `catalog` property containing nested `Catalog` types. This is required to support nested catalogs as specified by DCAT 3.

##### `contract-request-message-schema`
- Added improved constraints for `offer` property

##### `contract-offer-message-schema.json`
- Added improved constraints, including `target`
- Corrected message examples

##### `contract-negotiation-error-schema.json`
- Removed  "dct:description" property

##### `contract-agreement-message-schema.json`
- Fixed examples (e.g., `operator` instead of `operand`)

##### `transfer-request-message-schema.json`
- Changed `endpointType` from `DataAddress` as it is not mentioned in the spec (other than the examples) and is not needed as this can be inferred by the `dct:format` of the request

# ODRL profile

- Added ODRL context to fix a number of problems: redefinition of @id as uid, fix `neg` typo to `neq`
- `assigner` and `assigner` MUST only be specified on type `Agreement`. For example, not allowed on type `Offer` as seen [here](https://w3c.github.io/poe/model/#policy-offer)
- `target` can only be specified on the `Agreement` type and not on an `Offer` or any other property types such as `Permission`
- properties not in schema (e.g. `rightOperandReference`) do not need to be supported
- Made `rightOperand` a literal string. IRIs, arrays, and object types do not need to be supported but could be.
- Removed all other terms that are not required.


## Open Questions (dataset-schema.json)
- Do we want to support  the `servesDataset` property on `DataService`? Increases complexity for catalog handling datasets can be contained directly in the catalog or the DataService?

## TODO
- Remove `assigner` from all example offer and message offer files. The property should only be present in `Agreement`. For example, dataset, catalog, and offer examples.

**Comment by mkollenstart** [comment]
In general, I agree with a lot of the points mentioned.
But a couple of remarks come to mind after a quick look:

- The DCAT schema/context is now very limited, which indeed helps interoperability right now. But I foresee that additional properties will be used, both from DCAT (v3) and outside (e.g. HealthDCAT-AP). Which would require an additional set of schemas and context definitions to prevent a situation where part of the document is without prefixes and another part is with prefixes. So I would suggest to include at least DCAT v3, and make sure to document in e.g. the best practices how to properly deal with inclusion of additional functionalities.
- Similarly, for ODRL, additional profiles that describe the specific operands/operators will be required for actual usage.


Will have a closer look later on.

**Comment by jimmarino** [comment]
> In general, I agree with a lot of the points mentioned. But a couple of remarks come to mind after a quick look:
> 
> * The DCAT schema/context is now very limited, which indeed helps interoperability right now. But I foresee that additional properties will be used, both from DCAT (v3) and outside (e.g. HealthDCAT-AP). Which would require an additional set of schemas and context definitions to prevent a situation where part of the document is without prefixes and another part is with prefixes. So I would suggest to include at least DCAT v3, and make sure to document in e.g. the best practices how to properly deal with inclusion of additional functionalities.
> * Similarly, for ODRL, additional profiles that describe the specific operands/operators will be required for actual usage.
> 
> Will have a closer look later on.

I would like us to recommend industries, dataspaces, etc. create profiles that have additional Json-Ld contexts, policy definitions, etc. To your point, we should create a document providing a guide to how this is done. Implementations can (optionally) provide facilities for configuring these additional contexts (if they are Json-Ld-aware) or simply process the properties if they use plain Json. 

I want to move these terms (particularly the ODRL ones) out of the core DSP specification because they have no normative semantic definition and are therefore not verifiable. Many are also very industry-specific and are often not applicable.
