### ISSUE TITLE
add reference to additional credential exchange protocol

### ISSUE THREAD

**Issue by ticapix** [eclipse-dataspace-protocol-base/DataspaceProtocol#65]
Dear,

As mentioned by @arnoweiss, to follow the PR process, I'm opening an issue for https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/pull/63

## Improvement requests

**Type**: `non-normative`

- Update reference to DCP instead of IATP
- Add reference to OID4VC

## Why Is the Feature Desired?

There are 2 changes:
- Per decision of the EDWG to rename IATP by DCP
- Proposal to explicitly mention other possible protocols, such as OID4VC to
    - avoid the creation of an artificial gravity effect around the same self-referencing protocol drafts DSP <-> DCP.
    - avoid the creation of a misrepresentation that DSP could only work with DCP.
    - ensure broader adoption of DSP from non-EDC based connector.

## Solution Proposal

https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/pull/63

Best
Pierre

**Comment by jimmarino** [comment]
Please see my comments in the PR regarding OpenId4. I will not approve the PR unless the OpenId reference is removed for the reasons I stated.

Regarding the EDWG, we can have that discussion there, but it was very clearly stated and agreed to that all EDWG profile specifications must be compatible with DSP and DCP. They serve as the baseline interop for data spaces using DSP and a decentralized identity architecture.

**Comment by ticapix** [comment]
Hi @jimmarino,

Copy/pasting my reply to your comment on the PR.

Your message is raising the concern about the creation of a mandatory dependency between DSP and DCP. I don't recall that such a decision was voted in the EDWG.

On the opposite, there is a decision at the EDWG that each protocol has it's own TCK, making it possible by design, to be compatible with DSP with or without DCP.

For me to remove the reference to OpenId4VC, could you point to the normative parts of DSP that:

1. mandate that only DCP can be used
2. only non-human interaction are eligible for DSP.

?

Best regards,
Pierre

**Comment by ssteinbuss** [comment]
overtaken by event. fixed #58
