### ISSUE TITLE
Add missing properties to autogenerated property tables

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-dataspace-protocol-base/DataspaceProtocol#80]
# Feature Request

https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/pull/77 introduced the capability to generate HTML tables from json-schemas. The generated artifacts are all missing 
1. the context property
2. links to other object definitions aside from json primitives.

## Which Areas Would Be Affected?

`generateTablesFromSchemas` plugin

**Type**: `non-normative` 
## Why Is the Feature Desired?

functional completeness

**Comment by jimmarino** [comment]
@arnoweiss can you point out which artifacts are missing a context? The top-level *Message types should have `@context` properties (which they do), but not other types such as `Agreement`, `DataAddress`, etc. Maybe there are a few I missed?

**Comment by arnoweiss** [comment]
For `Catalog` and `Dataset` I didn't get any `@context` properties generated.

```html
<table class="message-table">
    <tr>
        <td class="message-class" colspan="3">Catalog</td>
    </tr>
    <tr>
        <td class="message-properties-heading" colspan="3">Required properties</td>
    </tr>
    <tr>
        <td class="code">@id</td>
    </tr>
    <tr>
        <td class="code">@type</td>
        <td>string</td>
        <td>Value must be <span class="code">Catalog</span></td>
    </tr>
    <tr>
        <td class="message-properties-heading" colspan="3">Optional properties</td>
    </tr>
    <tr>
        <td class="code">catalog</td>
        <td>array</td>
        <td></td>
    </tr>
    <tr>
        <td class="code">dataset</td>
        <td>array</td>
        <td></td>
    </tr>
    <tr>
        <td class="code">distribution</td>
        <td>array</td>
        <td></td>
    </tr>
    <tr>
        <td class="code">hasPolicy</td>
        <td>array</td>
        <td></td>
    </tr>
    <tr>
        <td class="code">service</td>
        <td>array</td>
        <td></td>
    </tr>
</table>

```

**Comment by jimmarino** [comment]
Ah that's because those aren't message types and shouldn't have a context. For example, both can be referenced in another catalog. In that case, the embedded type must not have a context. 

Let me look at adding a *Message type for each one to handle the root case where `@context` is required.

**Comment by jimmarino** [comment]
Looking at this further, there is a `RootCatalog` type that requires `@context`. This type is used for top level catalogs, while embedded catalogs (where there should be no `@context`) use the `Catalog` type.

There is a bug with `Dataset` where that type (without the `@context` requirement) is used as a top-level response message, which is a bug. I fixed this by introducing a `RootDataset` type in #85.
