### ISSUE TITLE
Embed textual message property definitions in json schema

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-dataspace-protocol-base/DataspaceProtocol#83]
# Feature Request

To autogenerate the descriptions too, the source of truth should be the json schemas. 

## Which Areas Would Be Affected?

message definitions

**Type**:  `non-normative`

## Why Is the Feature Desired?

remove manual error-prone process of joining the auto-generated and textual components of the spec-text

## Solution Proposal

- add a property like "$comment" to the json-schemas
- manually move the descriptions from the spec into the json-schemas
- generate it into an appropriate html structure using `./gradlew generateTablesFromSchemas`
- integrate with website build

**Comment by juliapampus** [comment]
#51
