### ISSUE TITLE
Update Contribution Guidelines and Define Paths to Contributor and Committer Status

### ISSUE THREAD

**Issue by ssteinbuss** [eclipse-dataspace-protocol-base/DataspaceProtocol#9]
To foster a welcoming and productive community, it is important to have clear and comprehensive contribution guidelines. These guidelines should not only outline how to contribute to the project but also provide a clear path for contributors to achieve the status of a contributor and a committer.

## Proposed Solution

* Review Existing Contribution Guidelines: Examine the current contribution guidelines to identify any gaps or areas for improvement.
* Define Paths to Contributor and Committer Status: Establish clear criteria and processes for contributors to achieve the status of a recognized contributor and a committer. This should include:
   * Contributor Status: Guidelines on how to become a recognized contributor, including the types of contributions that are valued (e.g., code, documentation, issue triage), expected conduct, and the review process.
   * Committer Status: Criteria for becoming a committer, such as demonstrated expertise in the project, a history of quality contributions, and community involvement. Also, outline the responsibilities and privileges that come with committer status.
* Update Contribution Guidelines: Revise the contribution guidelines to include the new paths to contributor and committer status. Ensure the guidelines are clear, detailed, and accessible to all potential contributors.
* Document the Process: Create a clear, step-by-step process for contributors to follow, including:
   * How to submit contributions (e.g., pull requests, issues)
   * How contributions are reviewed and accepted
   * How to apply for or be nominated for contributor or committer status
   * Expectations and responsibilities for contributors and committers
* Communicate the Changes: Update the README and other relevant documentation to reference the new contribution guidelines. Announce the changes to the community through appropriate channels (e.g., mailing list, GitHub Discussions).

## Action Items

- [ ] Review and revise the current contribution guidelines.
- [ ] Define clear criteria and processes for achieving contributor and committer status.
- [ ] Update the contribution guidelines with the new information.
- [ ] Document the step-by-step process for contributing and achieving new statuses.
- [ ] Communicate the updated guidelines to the community.

**Comment by juliapampus** [comment]
Some guidelines provided by the EDC project:
- [committer retirement](https://github.com/eclipse-edc/docs/tree/main/developer/decision-records/2023-07-06-committer-retirement)
- [onboarding contributors](https://github.com/eclipse-edc/docs/tree/main/developer/decision-records/2023-06-19-onboarding-contributors)
- EF's [project roles](https://www.eclipse.org/projects/handbook/#roles)

I will come up with an example `CONTRIBUTING.md`
